import { defineConfig } from "kubb/config";
import { pluginFetch } from "@kubb/plugin-fetch";
import { pluginReactQuery } from "@kubb/plugin-react-query";
import { pluginTs } from "@kubb/plugin-ts";

const generatedBanner = (meta: { isBarrel?: boolean; isAggregation?: boolean }) =>
	meta.isBarrel || meta.isAggregation ? "" : "/* Generated by Kubb. Do not edit. */";

export default defineConfig({
	name: "lambda-api-client",
	input: "../../apps/api/openapi/openapi.json",
	output: { path: "./src/generated", clean: true },
	plugins: [
		pluginTs({
			output: {
				path: "types",
				mode: "directory",
				barrel: { type: "named" },
				banner: generatedBanner,
			},
		}),
		pluginFetch({
			output: {
				path: "client",
				mode: "directory",
				barrel: { type: "named" },
				banner: generatedBanner,
			},
			group: { type: "tag" },
		}),
		pluginReactQuery({
			client: "fetch",
			exclude: [{ type: "contentType", pattern: /^text\/event-stream$/ }],
			hooks: false,
			output: {
				path: "query",
				mode: "directory",
				barrel: { type: "named" },
				banner: generatedBanner,
			},
			group: { type: "tag" },
		}),
	],
});
