import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { Type } from "typebox";
import * as publicExports from "../src/index.js";
import { discoverReusableSchemas, renderReusableSchemas } from "./generate-schema-registry.js";

describe("reusable schema registry generator", () => {
	it("discovers public TypeBox schemas with non-empty ids", () => {
		const schemas = discoverReusableSchemas(publicExports);
		const project = schemas.find(schema => schema.exportName === "ProjectSchema");

		assert.equal(project?.id, "Project");
		assert.ok(schemas.every(schema => schema.schema["~kind"]));
	});

	it("ignores route-local schemas without ids", () => {
		const schemas = discoverReusableSchemas({
			LocalSchema: Type.Object({}),
			unrelated: { value: true },
		});

		assert.deepEqual(schemas, []);
	});

	it("rejects an object with an id that is not a TypeBox schema", () => {
		assert.throws(
			() => discoverReusableSchemas({ invalid: { $id: "Invalid" } }),
			/has \$id but is not a TypeBox schema/,
		);
	});

	it("rejects empty ids and duplicate ids", () => {
		assert.throws(
			() => discoverReusableSchemas({ EmptySchema: Type.Object({}, { $id: "  " }) }),
			/empty or invalid \$id/,
		);

		assert.throws(
			() => discoverReusableSchemas({ Padded: Type.Object({}, { $id: " Project " }) }),
			/empty or invalid \$id/,
		);

		assert.throws(
			() =>
				discoverReusableSchemas({
					FirstSchema: Type.Object({}, { $id: "Duplicate" }),
					SecondSchema: Type.String({ $id: "Duplicate" }),
				}),
			/ Duplicate /,
		);
	});

	it("sorts output by id and renders repeated input byte-identically", () => {
		const first = renderReusableSchemas(
			discoverReusableSchemas({
				ZSchema: Type.Object({}, { $id: "Z" }),
				ASchema: Type.Object({}, { $id: "A" }),
			}),
		);
		const second = renderReusableSchemas(
			discoverReusableSchemas({
				ASchema: Type.Object({}, { $id: "A" }),
				ZSchema: Type.Object({}, { $id: "Z" }),
			}),
		);

		assert.equal(first, second);
		assert.ok(first.indexOf("ASchema") < first.indexOf("ZSchema"));
	});

	it("sorts by code units, not locale", () => {
		const rendered = renderReusableSchemas(
			discoverReusableSchemas({
				lower: Type.Object({}, { $id: "alpha" }),
				upper: Type.Object({}, { $id: "Beta" }),
			}),
		);
		// Code-unit order: uppercase 'B' (0x42) sorts before lowercase 'a' (0x61).
		// Locale collation would order "alpha" before "Beta"; code units order "Beta" first.
		assert.ok(rendered.indexOf("upper") < rendered.indexOf("lower"));
	});

	it("renders empty registry without invalid import", () => {
		assert.equal(
			renderReusableSchemas([]),
			`/* Generated by generate-schema-registry.ts. Do not edit. */

export const reusableSchemas = [

] as const;
`,
		);
	});
});
