import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { IsKind, IsSchema, type TSchema } from "typebox";
import * as publicExports from "../src/index.js";

type TypeBoxSchema = TSchema & Record<string, unknown> & { "~kind": string };
export type ReusableSchema = {
	exportName: string;
	id: string;
	schema: TypeBoxSchema;
};

function isObject(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null;
}

function compareStrings(left: string, right: string): number {
	return left < right ? -1 : left > right ? 1 : 0;
}

function isTypeBoxSchema(value: unknown): value is TypeBoxSchema {
	if (!IsSchema(value) || !isObject(value) || Array.isArray(value)) return false;
	const kind = value["~kind"];
	return typeof kind === "string" && IsKind(value, kind);
}

function hasOwnId(value: Record<string, unknown>): boolean {
	return Object.prototype.hasOwnProperty.call(value, "$id");
}

export function discoverReusableSchemas(exports: Record<string, unknown>): ReusableSchema[] {
	const reusable: ReusableSchema[] = [];
	const ids = new Map<string, string>();

	for (const [exportName, value] of Object.entries(exports)) {
		if (!isTypeBoxSchema(value)) {
			if (isObject(value) && hasOwnId(value)) {
				throw new Error(`Export ${exportName} has $id but is not a TypeBox schema.`);
			}
			continue;
		}

		if (!hasOwnId(value)) continue;
		const id = value.$id;
		if (typeof id !== "string" || id.length === 0 || id !== id.trim()) {
			throw new Error(`Export ${exportName} has an empty or invalid $id.`);
		}

		const previousExport = ids.get(id);
		if (previousExport) {
			throw new Error(
				`Duplicate reusable schema $id "${id}" on ${previousExport} and ${exportName}.`,
			);
		}
		ids.set(id, exportName);
		reusable.push({ exportName, id, schema: value });
	}

	return reusable.sort(
		(left, right) =>
			compareStrings(left.id, right.id) || compareStrings(left.exportName, right.exportName),
	);
}

export function renderReusableSchemas(schemas: ReusableSchema[]): string {
	const imports = schemas.map(schema => `\t${schema.exportName},`).join("\n");
	const values = schemas.map(schema => `\t${schema.exportName},`).join("\n");
	const importBlock = schemas.length
		? `import {
${imports}
} from "../index.js";

`
		: "";
	return `/* Generated by generate-schema-registry.ts. Do not edit. */

${importBlock}export const reusableSchemas = [
${values}
] as const;
`;
}

export async function generateSchemaRegistry() {
	const outputPath = resolve(import.meta.dirname, "../src/generated/reusable-schemas.ts");
	await mkdir(dirname(outputPath), { recursive: true });
	await writeFile(
		outputPath,
		renderReusableSchemas(discoverReusableSchemas(publicExports)),
		"utf8",
	);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
	await generateSchemaRegistry();
}
